In [60]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from sqlalchemy.sql import text
import warnings
import sys
import os # Esto sube un nivel en las carpetas para encontrar la raíz del proyecto
from dotenv import load_dotenv

sys.path.append(os.path.abspath(".."))

import src.db_builder as db

# Verificar dónde está buscando el .env
print("Directorio actual:", os.getcwd())

# Cargar y comprobar variables
load_dotenv("../.env")

Directorio actual: c:\Users\dacil\Desktop\Adalab\proyectos\Proyectos\e-commerce-operations-insights\notebooks

True

In [61]:
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [62]:
df_data = pd.read_csv("../files/processed/dataco_supply_chain.csv", sep=None, engine="python", encoding="latin-1")

In [63]:
df_data.sample(5)

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,delivery_date,order_date,order_time
67650,DEBIT,4,4,62.89,149.73,Shipping on time,0,37,Electronics,Caguas,Puerto Rico,Richard,11576,Andrade,Corporate,Puerto Rico,1987 Burning Rabbit Crescent,725,6,Outdoors,18.219297,-66.370522,San Francisco,Estados Unidos,11576,37808,823,6.24,0.04,94348,51.99,0.42,3,155.97,149.73,62.89,West of USA,COMPLETE,823,37,Titleist Pro V1x High Numbers Personalized Go,51.99,Standard Class,07-09-2016,07-05-2016,21:28
57052,DEBIT,6,4,30.71,122.84,Late delivery,1,13,Electronics,Caguas,Puerto Rico,Jessica,6440,Smith,Consumer,Puerto Rico,6829 Cozy River Landing,725,3,Footwear,18.293242,-66.370544,Langenfeld,Alemania,6440,19925,282,5.12,0.04,49810,31.99,0.25,4,127.96,122.84,30.71,Western Europe,COMPLETE,282,13,Under Armour Women's Ignite PIP VI Slide,31.99,Standard Class,10-24-2015,10-18-2015,20:15
16913,CASH,3,2,28.13,225.00,Late delivery,1,24,Women's Apparel,Philadelphia,EE. UU.,Mary,9214,Smith,Consumer,Pennsylvania,1723 Tawny Via,19148,5,Golf,39.923210,-75.163086,Managua,Nicaragua,9214,60432,502,25.00,0.10,151227,50.00,0.13,5,250.00,225.00,28.13,Central America,CLOSED,502,24,Nike Men's Dri-FIT Victory Golf Polo,50.00,Second Class,06-04-2017,06-01-2017,03:40
42149,DEBIT,2,1,77.93,248.98,Late delivery,1,43,Camping & Hiking,Morganton,EE. UU.,Raymond,7724,Smith,Consumer,North Carolina,3428 Hidden Moor,28655,7,Fan Shop,35.835480,-81.632332,San Francisco de MacorÃ­s,RepÃºblica Dominicana,7724,53835,957,51.00,0.17,134589,299.98,0.31,1,299.98,248.98,77.93,Caribbean,COMPLETE,957,43,Diamondback Women's Serene Classic Comfort Bi,299.98,First Class,02-26-2017,02-24-2017,20:26
14608,DEBIT,4,4,28.80,383.96,Shipping on time,0,9,Cardio Equipment,Memphis,EE. UU.,Ronald,7474,Levy,Corporate,Tennessee,1865 Lazy Lake Pines,38109,3,Footwear,35.094418,-90.018173,TorreÃ³n,MÃ©xico,7474,4203,191,16.00,0.04,10500,99.99,0.08,4,399.96,383.96,28.80,Central America,COMPLETE,191,9,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class,03-07-2015,03-03-2015,08:08

In [64]:
departments = df_data[["department_id", "department_name"]].drop_duplicates(subset=["department_id"]).reset_index(drop=True)

In [65]:
departments.sample(5)

   department_id department_name
9             11        Pet Shop
0              2         Fitness
6             10      Technology
5              7        Fan Shop
3              3        Footwear

In [66]:
categories = df_data[['category_id', 'category_name']].drop_duplicates(subset=['category_id']).reset_index(drop=True)

In [67]:
categories.sample(5)

    category_id    category_name
48           74             Toys
2            29    Shop By Sport
26           16  As Seen on  TV!
32           45          Fishing
16           64        Computers

In [68]:
products = df_data[["product_card_id", "product_name", "product_price", "category_id"]].drop_duplicates(subset=["product_card_id"]).reset_index(drop=True)

In [69]:
products.sample(5)

,product_card_id,product_name,product_price,category_id
10,818,Titleist Pro V1x Golf Balls,47.99,37
73,982,insta-bed Neverflat Air Mattress,149.99,44
8,828,Bridgestone e6 Straight Distance NFL San Dieg,31.99,37
28,885,Team Golf St. Louis Cardinals Putter Grip,24.99,40
65,78,Nike Kids' Grade School KD VI Basketball Shoe,99.99,5

In [70]:
customers = df_data[['customer_id', 'customer_fname', 'customer_lname', 
                    'customer_segment', 'customer_street', 
                    'customer_city', 'customer_state', 'customer_zipcode', 'customer_country',
                    'latitude', 'longitude']].drop_duplicates(subset=['customer_id']).reset_index(drop=True)

In [71]:
customers.head(5)

,customer_id,customer_fname,customer_lname,customer_segment,customer_street,customer_city,customer_state,customer_zipcode,customer_country,latitude,longitude
0,20755,Cally,Holloway,Consumer,5365 Noble Nectar Island,Caguas,Puerto Rico,725,Puerto Rico,18.251453,-66.037056
1,19492,Irene,Luna,Consumer,2679 Rustic Loop,Caguas,Puerto Rico,725,Puerto Rico,18.279451,-66.037064
2,19491,Gillian,Maldonado,Consumer,8510 Round Bear Gate,San Jose,California,95125,EE. UU.,37.292233,-121.881279
3,19490,Tana,Tate,Home Office,3200 Amber Bend,Los Angeles,California,90027,EE. UU.,34.125946,-118.291016
4,19489,Orli,Hendricks,Corporate,8671 Iron Anchor Corners,Caguas,Puerto Rico,725,Puerto Rico,18.253769,-66.037048

In [72]:
orders = df_data[['order_id', 'customer_id', 'department_id', 'type', 'order_date', 
                  'order_time', 'order_status', 'order_city', 'order_country', 
                  'order_region', 'shipping_mode', 'delivery_date', 'days_for_shipping_real', 
                  'days_for_shipment_scheduled', 'delivery_status', 
                  'late_delivery_risk']].drop_duplicates(subset=['order_id']).reset_index(drop=True)

In [73]:
orders.tail()

,order_id,customer_id,department_id,type,order_date,order_time,order_status,order_city,order_country,order_region,shipping_mode,delivery_date,days_for_shipping_real,days_for_shipment_scheduled,delivery_status,late_delivery_risk
65747,26773,5857,7,CASH,01-26-2016,19:25,CLOSED,Ho Chi Minh City,Vietnam,Southeast Asia,First Class,01-28-2016,2,1,Late delivery,1
65748,26463,9230,7,PAYMENT,01-22-2016,06:49,PENDING_PAYMENT,Ezhou,China,Eastern Asia,Standard Class,01-26-2016,4,4,Shipping on time,0
65749,26383,4618,7,CASH,01-21-2016,02:47,CLOSED,Tawau,Malasia,Southeast Asia,Second Class,01-25-2016,4,2,Late delivery,1
65750,26327,989,7,DEBIT,01-20-2016,07:10,ON_HOLD,Semarang,Indonesia,Southeast Asia,Standard Class,01-23-2016,3,4,Advance shipping,0
65751,26118,6251,7,TRANSFER,01-17-2016,05:56,SUSPECTED_FRAUD,Ratlam,India,South Asia,Standard Class,01-21-2016,4,4,Shipping canceled,0

In [74]:
order_items = df_data[['order_item_id', 'order_id', 'product_card_id', 'order_item_quantity',
                    'order_item_product_price', 'order_item_discount', 
                    'order_item_discount_rate', 'sales', 'order_item_total', 
                    'order_item_profit_ratio', 'benefit_per_order']].drop_duplicates(subset=['order_item_id']).reset_index(drop=True)

In [75]:
order_items.sample(5)

,order_item_id,order_id,product_card_id,order_item_quantity,order_item_product_price,order_item_discount,order_item_discount_rate,sales,order_item_total,order_item_profit_ratio,benefit_per_order
136090,38151,15256,365,3,59.99,7.20,0.04,179.97,172.77,0.36,62.72
35705,174231,70916,1352,1,252.88,63.22,0.25,252.88,189.66,0.33,61.64
7779,114753,45912,191,2,99.99,36.00,0.18,199.98,163.98,0.35,57.39
21100,68593,27392,403,1,129.99,16.90,0.13,129.99,113.09,0.10,11.31
113418,13249,5305,1014,2,49.98,14.99,0.15,99.96,84.97,0.29,24.64

In [76]:
db.get_connection_string(db_name=None, user=None, password=None, host=None, port=None)

'mysql+pymysql://root:AlumnaAdalab@127.0.0.1:3306/'

#### Carga a SQL de dataco_supply_chain

In [77]:
db.create_database_if_not_exists("dataco")

✅ Base de datos 'dataco' verificada/creada con éxito.

In [78]:
db.load_dataframe_to_mysql(departments, "departments", "dataco")

✅ Datos cargados exitosamente en la tabla 'departments'.

In [79]:
db.set_primary_key("departments", "department_id", "dataco")

✅ Clave primaria 'department_id' (INT) asignada en 'departments'.

In [80]:
db.load_dataframe_to_mysql(categories, "categories", "dataco")

✅ Datos cargados exitosamente en la tabla 'categories'.

In [81]:
db.set_primary_key("categories", "category_id", "dataco")

✅ Clave primaria 'category_id' (INT) asignada en 'categories'.

In [82]:
db.load_dataframe_to_mysql(products, "products", "dataco")

✅ Datos cargados exitosamente en la tabla 'products'.

In [83]:
db.set_primary_key("products", "product_card_id", "dataco")

✅ Clave primaria 'product_card_id' (INT) asignada en 'products'.

In [84]:
db.set_foreign_key("products", "categories", "category_id", "dataco")

🔗 Relación creada: products.category_id ➡️ categories.category_id

In [85]:
db.load_dataframe_to_mysql(customers, "customers", "dataco")

✅ Datos cargados exitosamente en la tabla 'customers'.

In [86]:
db.set_primary_key("customers", "customer_id", "dataco")

✅ Clave primaria 'customer_id' (INT) asignada en 'customers'.

In [87]:
db.load_dataframe_to_mysql(orders, "orders", "dataco")

✅ Datos cargados exitosamente en la tabla 'orders'.

In [88]:
db.set_primary_key("orders", "order_id", "dataco")

✅ Clave primaria 'order_id' (INT) asignada en 'orders'.

In [89]:
db.set_foreign_key("orders", "customers", "customer_id", "dataco")

🔗 Relación creada: orders.customer_id ➡️ customers.customer_id

In [90]:
db.set_foreign_key("orders", "departments", "department_id", "dataco")

🔗 Relación creada: orders.department_id ➡️ departments.department_id

In [91]:
db.load_dataframe_to_mysql(order_items, "order_items", "dataco")

✅ Datos cargados exitosamente en la tabla 'order_items'.

In [92]:
db.set_primary_key("order_items", "order_item_id", "dataco")

✅ Clave primaria 'order_item_id' (INT) asignada en 'order_items'.

In [93]:
db.set_foreign_key("order_items", "orders", "order_id", "dataco")

🔗 Relación creada: order_items.order_id ➡️ orders.order_id

In [94]:
db.set_foreign_key("order_items", "products", "product_card_id", "dataco")

🔗 Relación creada: order_items.product_card_id ➡️ products.product_card_id

#### Carga a SQL de token_access_logs

In [95]:
df_token = pd.read_csv("../files/processed/token_access_logs.csv")

In [96]:
df_token.sample(5)

,product,category,department,ip,date,datetime
286227,Nike Men's Dri-FIT Victory Golf Polo,women's apparel,golf,71.34.106.10,09-14-2017,22:22
390759,SOLE E35 Elliptical,strength training,footwear,77.194.54.210,09-24-2017,14:04
254660,Diamondback Women's Serene Classic Comfort Bi,camping & hiking,fan shop,62.245.233.53,12-30-2017,16:53
445376,Stiga Master Series ST3100 Competition Indoor,hockey,fitness,42.127.123.164,10-02-2017,15:53
390423,adidas Men's Germany Black Crest Away Tee,girls' apparel,golf,30.73.15.79,01-20-2018,06:36

In [97]:
# Paso 1: Crea la columna 'id' asignándole el rango (sin reasignar df_token aquí)
df_token["id"] = range(1, len(df_token) + 1)

# Paso 2: Reorganiza las columnas para poner 'id' al principio
columnas = ["id"] + [col for col in df_token.columns if col != "id"]
df_token = df_token[columnas]

In [98]:
db.load_dataframe_to_mysql(df_token, "access_web", "dataco")

✅ Datos cargados exitosamente en la tabla 'access_web'.

In [99]:
db.set_primary_key("access_web", "id", "dataco", data_type="VARCHAR(25)")

✅ Clave primaria 'id' (VARCHAR(25)) asignada en 'access_web'.