In [146]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from sqlalchemy.sql import text
import warnings
import sys
import os # Esto sube un nivel en las carpetas para encontrar la raíz del proyecto
from dotenv import load_dotenv

sys.path.append(os.path.abspath(".."))

import src.db_builder as db

# Verificar dónde está buscando el .env
print("Directorio actual:", os.getcwd())

# Cargar y comprobar variables
load_dotenv("../.env")

Directorio actual: c:\Users\fabih\Desktop\CREATOR\data\data_e-commerce\e-commerce-operations-insights\notebooks

True

In [147]:
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [148]:
df_data = pd.read_csv("../files/processed/dataco_supply_chain.csv", sep=None, engine="python", encoding="latin-1")

In [149]:
df_data.sample(5)

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,delivery_date,order_date,order_time
64316,DEBIT,4,2,113.39,251.98,Late delivery,1,43,Camping & Hiking,North Richland Hills,EE. UU.,Emma,11965,Noble,Consumer,TX,417 Quiet Grove Ramp,76180,7,Fan Shop,32.842922,-97.226158,Madrid,EspaÃ±a,11965,16618,957,48.0,0.16,41536,299.98,0.45,1,299.98,251.98,113.39,Southern Europe,COMPLETE,957,43,Diamondback Women's Serene Classic Comfort Bi,299.98,Second Class,09-04-2015,08-31-2015,13:40
46213,PAYMENT,2,4,14.14,113.09,Advance shipping,0,18,Men's Footwear,Garden Grove,EE. UU.,Sara,4157,Brewer,Corporate,CA,5908 Shady Log Forest,92840,4,Apparel,33.773865,-118.026451,Anshan,China,4157,28671,403,16.9,0.13,71764,129.99,0.13,1,129.99,113.09,14.14,Eastern Asia,PENDING_PAYMENT,403,18,Nike Men's CJ Elite 2 TD Football Cleat,129.99,Standard Class,02-25-2016,02-23-2016,12:22
96721,DEBIT,2,1,-109.53,66.38,Late delivery,1,29,Shop By Sport,Moreno Valley,EE. UU.,Mary,2981,Spence,Home Office,CA,5127 Sleepy Via,92557,5,Golf,33.947170,-117.253624,Puebla,MÃ©xico,2981,54911,627,13.6,0.17,137341,39.99,-1.65,2,79.98,66.38,-109.53,Central America,COMPLETE,627,29,Under Armour Girls' Toddler Spine Surge Runni,39.99,First Class,03-14-2017,03-12-2017,13:25
126448,PAYMENT,5,4,40.98,126.09,Late delivery,1,18,Men's Footwear,Caguas,Puerto Rico,Paul,5115,Chang,Consumer,PR,6864 High Gate Canyon,725,4,Apparel,18.265753,-66.370506,Helsinki,Finlandia,5115,65919,403,3.9,0.03,164727,129.99,0.33,1,129.99,126.09,40.98,Northern Europe,PENDING_PAYMENT,403,18,Nike Men's CJ Elite 2 TD Football Cleat,129.99,Standard Class,08-25-2017,08-20-2017,06:00
85219,TRANSFER,4,4,-48.90,299.99,Shipping on time,0,45,Fishing,Scottsdale,EE. UU.,Mary,505,Smith,Corporate,AZ,6281 Amber Autumn Hill,85254,7,Fan Shop,29.407394,-98.658951,Cologne,Alemania,505,11498,1004,100.0,0.25,28771,399.98,-0.16,1,399.98,299.99,-48.90,Western Europe,PENDING,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.98,Standard Class,06-21-2015,06-17-2015,19:54

In [150]:
locations = df_data[['latitude', 'longitude']].drop_duplicates().reset_index(drop=True)
locations['location_id'] = locations.index + 1
locations = locations[['location_id', 'latitude', 'longitude']]

In [151]:
locations.tail(5)

       location_id   latitude  longitude
11830        11831  18.275261 -66.037056
11831        11832  18.223066 -66.037056
11832        11833  18.240482 -66.037064
11833        11834  18.261297 -66.037056
11834        11835  18.242485 -66.370514

In [152]:
departments = df_data[["department_id", "department_name"]].drop_duplicates(subset=["department_id"]).reset_index(drop=True)

In [153]:
departments.sample(5)

   department_id department_name
4              6        Outdoors
2              5            Golf
7              8       Book Shop
0              2         Fitness
6             10      Technology

In [154]:
categories = df_data[['category_id', 'category_name']].drop_duplicates(subset=['category_id']).reset_index(drop=True)

In [155]:
categories.sample(5)

    category_id        category_name
0            73       Sporting Goods
18            2               Soccer
1            17               Cleats
11            3  Baseball & Softball
38           72         Pet Supplies

In [156]:
products = df_data[["product_card_id", "product_name", "product_price", "category_id"]].drop_duplicates(subset=["product_card_id"]).reset_index(drop=True)

In [157]:
products.sample(5)

,product_card_id,product_name,product_price,category_id
36,235,Under Armour Hustle Storm Medium Duffle Bag,34.99,11
75,1359,Adult dog supplies,84.40,72
52,172,Nike Women's Tempo Shorts,30.00,9
56,1347,Baby sweater,59.08,60
27,564,Nike Men's Deutschland Weltmeister Winners Bl,30.00,26

In [158]:
df_data = pd.merge(df_data, locations, on=['latitude', 'longitude'], how='left')

In [159]:
customers = df_data[['customer_id', 'customer_fname', 'customer_lname', 
                    'customer_segment', 'customer_street', 'location_id', 
                    'customer_city', 'customer_state', 'customer_zipcode', 'customer_country'
                    ]].drop_duplicates(subset=['customer_id']).reset_index(drop=True)

In [160]:
customers.head(5)

,customer_id,customer_fname,customer_lname,customer_segment,customer_street,location_id,customer_city,customer_state,customer_zipcode,customer_country
0,20755,Cally,Holloway,Consumer,5365 Noble Nectar Island,1,Caguas,PR,725,Puerto Rico
1,19492,Irene,Luna,Consumer,2679 Rustic Loop,2,Caguas,PR,725,Puerto Rico
2,19491,Gillian,Maldonado,Consumer,8510 Round Bear Gate,3,San Jose,CA,95125,EE. UU.
3,19490,Tana,Tate,Home Office,3200 Amber Bend,4,Los Angeles,CA,90027,EE. UU.
4,19489,Orli,Hendricks,Corporate,8671 Iron Anchor Corners,5,Caguas,PR,725,Puerto Rico

In [161]:
orders = df_data[['order_id', 'customer_id', 'department_id', 'type', 'order_date', 
                  'order_time', 'order_status', 'order_city', 'order_country', 
                  'order_region', 'shipping_mode', 'delivery_date', 'days_for_shipping_real', 
                  'days_for_shipment_scheduled', 'delivery_status', 
                  'late_delivery_risk']].drop_duplicates(subset=['order_id']).reset_index(drop=True)

In [162]:
orders.tail()

,order_id,customer_id,department_id,type,order_date,order_time,order_status,order_city,order_country,order_region,shipping_mode,delivery_date,days_for_shipping_real,days_for_shipment_scheduled,delivery_status,late_delivery_risk
65747,26773,5857,7,CASH,01-26-2016,19:25,CLOSED,Ho Chi Minh City,Vietnam,Southeast Asia,First Class,01-28-2016,2,1,Late delivery,1
65748,26463,9230,7,PAYMENT,01-22-2016,06:49,PENDING_PAYMENT,Ezhou,China,Eastern Asia,Standard Class,01-26-2016,4,4,Shipping on time,0
65749,26383,4618,7,CASH,01-21-2016,02:47,CLOSED,Tawau,Malasia,Southeast Asia,Second Class,01-25-2016,4,2,Late delivery,1
65750,26327,989,7,DEBIT,01-20-2016,07:10,ON_HOLD,Semarang,Indonesia,Southeast Asia,Standard Class,01-23-2016,3,4,Advance shipping,0
65751,26118,6251,7,TRANSFER,01-17-2016,05:56,SUSPECTED_FRAUD,Ratlam,India,South Asia,Standard Class,01-21-2016,4,4,Shipping canceled,0

In [163]:
order_items = df_data[['order_item_id', 'order_id', 'product_card_id', 'order_item_quantity',
                    'order_item_product_price', 'order_item_discount', 
                    'order_item_discount_rate', 'sales', 'order_item_total', 
                    'order_item_profit_ratio', 'benefit_per_order']].drop_duplicates(subset=['order_item_id']).reset_index(drop=True)

In [164]:
order_items.sample(5)

,order_item_id,order_id,product_card_id,order_item_quantity,order_item_product_price,order_item_discount,order_item_discount_rate,sales,order_item_total,order_item_profit_ratio,benefit_per_order
125266,27110,10833,1004,1,399.98,0.0,0.00,399.98,399.98,0.33,129.99
155367,58315,23289,191,4,99.99,48.0,0.12,399.96,351.96,0.31,110.16
151623,95039,38071,1004,1,399.98,36.0,0.09,399.98,363.98,0.00,0.00
164407,101856,40808,365,3,59.99,3.6,0.02,179.97,176.37,0.25,44.09
138033,144628,57804,1004,1,399.98,0.0,0.00,399.98,399.98,0.35,139.99

In [165]:
db.get_connection_string(db_name=None, user=None, password=None, host=None, port=None)

'mysql+pymysql://root:25401229@localhost:3306/'

#### Carga a SQL de dataco_supply_chain

In [166]:
db.create_database_if_not_exists("dataco")

✅ Base de datos 'dataco' verificada/creada con éxito.

In [167]:
db.load_dataframe_to_mysql(locations, "locations", "dataco")

✅ Datos cargados exitosamente en la tabla 'locations'.

In [168]:
db.set_primary_key("locations", "location_id", "dataco")

✅ Clave primaria 'location_id' (INT) asignada en 'locations'.

In [169]:
db.load_dataframe_to_mysql(departments, "departments", "dataco")

✅ Datos cargados exitosamente en la tabla 'departments'.

In [170]:
db.set_primary_key("departments", "department_id", "dataco")

✅ Clave primaria 'department_id' (INT) asignada en 'departments'.

In [171]:
db.load_dataframe_to_mysql(categories, "categories", "dataco")

✅ Datos cargados exitosamente en la tabla 'categories'.

In [172]:
db.set_primary_key("categories", "category_id", "dataco")

✅ Clave primaria 'category_id' (INT) asignada en 'categories'.

In [173]:
db.load_dataframe_to_mysql(products, "products", "dataco")

✅ Datos cargados exitosamente en la tabla 'products'.

In [174]:
db.set_primary_key("products", "product_card_id", "dataco")

✅ Clave primaria 'product_card_id' (INT) asignada en 'products'.

In [175]:
db.set_foreign_key("products", "categories", "category_id", "dataco")

🔗 Relación creada: products.category_id ➡️ categories.category_id

In [176]:
db.load_dataframe_to_mysql(customers, "customers", "dataco")

✅ Datos cargados exitosamente en la tabla 'customers'.

In [177]:
db.set_primary_key("customers", "customer_id", "dataco")

✅ Clave primaria 'customer_id' (INT) asignada en 'customers'.

In [178]:
db.set_foreign_key("customers", "locations", "location_id", "dataco")

🔗 Relación creada: customers.location_id ➡️ locations.location_id

In [179]:
db.load_dataframe_to_mysql(orders, "orders", "dataco")

✅ Datos cargados exitosamente en la tabla 'orders'.

In [180]:
db.set_primary_key("orders", "order_id", "dataco")

✅ Clave primaria 'order_id' (INT) asignada en 'orders'.

In [181]:
db.set_foreign_key("orders", "customers", "customer_id", "dataco")

🔗 Relación creada: orders.customer_id ➡️ customers.customer_id

In [182]:
db.set_foreign_key("orders", "departments", "department_id", "dataco")

🔗 Relación creada: orders.department_id ➡️ departments.department_id

In [183]:
db.load_dataframe_to_mysql(order_items, "order_items", "dataco")

✅ Datos cargados exitosamente en la tabla 'order_items'.

In [184]:
db.set_primary_key("order_items", "order_item_id", "dataco")

✅ Clave primaria 'order_item_id' (INT) asignada en 'order_items'.

In [185]:
db.set_foreign_key("order_items", "orders", "order_id", "dataco")

🔗 Relación creada: order_items.order_id ➡️ orders.order_id

In [186]:
db.set_foreign_key("order_items", "products", "product_card_id", "dataco")

🔗 Relación creada: order_items.product_card_id ➡️ products.product_card_id

#### Carga a SQL de token_access_logs

In [187]:
df_token = pd.read_csv("../files/processed/token_access_logs.csv")

In [188]:
df_token.sample(5)

,product,category,department,ip,date,datetime
26527,Glove It Imperial Golf Towel,trade-in,outdoors,166.41.139.5,12-04-2017,06:41
22767,Under Armour Men's Tech II T-Shirt,lacrosse,fitness,160.157.234.120,01-31-2018,19:13
134352,Under Armour Kids' Mercenary Slide,electronics,footwear,139.116.5.194,12-17-2017,12:53
149436,Nike Men's Dri-FIT Victory Golf Polo,women's apparel,golf,178.46.189.91,11-04-2017,16:21
130822,The North Face Women's Recon Backpack,hunting & shooting,fan shop,117.160.2.128,12-16-2017,13:31

In [189]:
# Paso 1: Crea la columna 'id' asignándole el rango (sin reasignar df_token aquí)
df_token["id"] = range(1, len(df_token) + 1)

# Paso 2: Reorganiza las columnas para poner 'id' al principio
columnas = ["id"] + [col for col in df_token.columns if col != "id"]
df_token = df_token[columnas]

In [190]:
db.load_dataframe_to_mysql(df_token, "access_web", "dataco")

✅ Datos cargados exitosamente en la tabla 'access_web'.

In [191]:
db.set_primary_key("access_web", "id", "dataco", data_type="VARCHAR(25)")

✅ Clave primaria 'id' (VARCHAR(25)) asignada en 'access_web'.