In [20]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from sqlalchemy.sql import text
import warnings
import sys
import os # Esto sube un nivel en las carpetas para encontrar la raíz del proyecto
from dotenv import load_dotenv

sys.path.append(os.path.abspath(".."))

import src.db_builder as db

# Verificar dónde está buscando el .env
print("Directorio actual:", os.getcwd())

# Cargar y comprobar variables
load_dotenv("../.env")

Directorio actual: c:\Users\fabih\Desktop\CREATOR\data\data_e-commerce\e-commerce-operations-insights\notebooks

True

In [21]:
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [22]:
df_data = pd.read_csv("../files/processed/dataco_supply_chain.csv", sep=None, engine="python", encoding="latin-1")

In [23]:
df_data.sample(5)

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,order_city,order_country,order_customer_id,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,delivery_date,order_date,order_time
120263,TRANSFER,6,4,-239.89,287.98,Shipping canceled,0,43,Camping & Hiking,Napa,EE. UU.,Anna,9527,Smith,Consumer,California,1663 Hidden Brook Island,94558,7,Fan Shop,Munich,Alemania,9527,62610,957,12.00,0.04,156519,299.98,-0.83,1,299.98,287.98,-239.89,Western Europe,CANCELED,957,43,Diamondback Women's Serene Classic Comfort Bi,299.98,Standard Class,07-08-2017,07-02-2017,22:43
160861,TRANSFER,6,4,-12.28,122.84,Late delivery,1,18,Men's Footwear,Caguas,Puerto Rico,Mary,10482,Rivera,Consumer,Puerto Rico,4992 Jagged Barn Close,725,4,Apparel,Richmond,Estados Unidos,10482,37195,403,7.15,0.06,92835,129.99,-0.10,1,129.99,122.84,-12.28,US Center,PROCESSING,403,18,Nike Men's CJ Elite 2 TD Football Cleat,129.99,Standard Class,07-02-2016,06-26-2016,22:42
150770,PAYMENT,2,1,-6.30,449.96,Late delivery,1,9,Cardio Equipment,Caguas,Puerto Rico,Mary,9830,Frey,Home Office,Puerto Rico,8988 Shady Park,725,3,Footwear,Madrid,EspaÃ±a,9830,19437,191,50.00,0.10,48577,99.99,-0.01,5,499.95,449.96,-6.30,Southern Europe,PENDING_PAYMENT,191,9,Nike Men's Free 5.0+ Running Shoe,99.99,First Class,10-13-2015,10-11-2015,17:17
152986,DEBIT,3,2,-72.94,387.98,Late delivery,1,45,Fishing,Caguas,Puerto Rico,Nicholas,978,Peters,Consumer,Puerto Rico,1669 Middle Common,725,7,Fan Shop,Philadelphia,Estados Unidos,978,32512,1004,12.00,0.03,81315,399.98,-0.19,1,399.98,387.98,-72.94,East of USA,COMPLETE,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.98,Second Class,04-22-2016,04-19-2016,14:03
153953,PAYMENT,2,4,4.20,83.99,Advance shipping,0,9,Cardio Equipment,Caguas,Puerto Rico,Frank,5238,Smith,Consumer,Puerto Rico,8905 Heather Bluff Place,725,3,Footwear,Buffalo Grove,Estados Unidos,5238,40436,191,16.00,0.16,100920,99.99,0.05,1,99.99,83.99,4.20,US Center,PENDING_PAYMENT,191,9,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class,08-15-2016,08-13-2016,06:10

In [24]:
departments = df_data[["department_id", "department_name"]].drop_duplicates(subset=["department_id"]).reset_index(drop=True)

In [25]:
departments.sample(5)

   department_id department_name
8              9      Discs Shop
7              8       Book Shop
3              3        Footwear
2              5            Golf
6             10      Technology

In [26]:
categories = df_data[['category_id', 'category_name']].drop_duplicates(subset=['category_id']).reset_index(drop=True)

In [27]:
categories.sample(5)

    category_id category_name
42           35   Golf Gloves
41           75   Video Games
32           45       Fishing
16           64     Computers
17            4    Basketball

In [28]:
products = df_data[["product_card_id", "product_name", "product_price", "category_id"]].drop_duplicates(subset=["product_card_id"]).reset_index(drop=True)

In [29]:
products.sample(5)

,product_card_id,product_name,product_price,category_id
59,1346,Sports Books,31.08,59
69,1355,Lawn mower,532.58,68
93,778,Bag Boy Beverage Holder,24.99,35
35,116,Nike Men's Comfort 2 Slide,44.99,6
18,1352,Industrial consumer electronics,252.88,65

In [30]:
customers = df_data[['customer_id', 'customer_fname', 'customer_lname', 
                    'customer_segment', 'customer_street', 
                    'customer_city', 'customer_state', 'customer_zipcode', 'customer_country',
                    ]].drop_duplicates(subset=['customer_id']).reset_index(drop=True)

In [31]:
customers.head(5)

,customer_id,customer_fname,customer_lname,customer_segment,customer_street,customer_city,customer_state,customer_zipcode,customer_country
0,20755,Cally,Holloway,Consumer,5365 Noble Nectar Island,Caguas,Puerto Rico,725,Puerto Rico
1,19492,Irene,Luna,Consumer,2679 Rustic Loop,Caguas,Puerto Rico,725,Puerto Rico
2,19491,Gillian,Maldonado,Consumer,8510 Round Bear Gate,San Jose,California,95125,EE. UU.
3,19490,Tana,Tate,Home Office,3200 Amber Bend,Los Angeles,California,90027,EE. UU.
4,19489,Orli,Hendricks,Corporate,8671 Iron Anchor Corners,Caguas,Puerto Rico,725,Puerto Rico

In [32]:
orders = df_data[['order_id', 'customer_id', 'department_id', 'type', 'order_date', 
                  'order_time', 'order_status', 'order_city', 'order_country', 
                  'order_region', 'shipping_mode', 'delivery_date', 'days_for_shipping_real', 
                  'days_for_shipment_scheduled', 'delivery_status', 
                  'late_delivery_risk']].drop_duplicates(subset=['order_id']).reset_index(drop=True)

In [33]:
orders.tail()

,order_id,customer_id,department_id,type,order_date,order_time,order_status,order_city,order_country,order_region,shipping_mode,delivery_date,days_for_shipping_real,days_for_shipment_scheduled,delivery_status,late_delivery_risk
65747,26773,5857,7,CASH,01-26-2016,19:25,CLOSED,Ho Chi Minh City,Vietnam,Southeast Asia,First Class,01-28-2016,2,1,Late delivery,1
65748,26463,9230,7,PAYMENT,01-22-2016,06:49,PENDING_PAYMENT,Ezhou,China,Eastern Asia,Standard Class,01-26-2016,4,4,Shipping on time,0
65749,26383,4618,7,CASH,01-21-2016,02:47,CLOSED,Tawau,Malasia,Southeast Asia,Second Class,01-25-2016,4,2,Late delivery,1
65750,26327,989,7,DEBIT,01-20-2016,07:10,ON_HOLD,Semarang,Indonesia,Southeast Asia,Standard Class,01-23-2016,3,4,Advance shipping,0
65751,26118,6251,7,TRANSFER,01-17-2016,05:56,SUSPECTED_FRAUD,Ratlam,India,South Asia,Standard Class,01-21-2016,4,4,Shipping canceled,0

In [34]:
order_items = df_data[['order_item_id', 'order_id', 'product_card_id', 'order_item_quantity',
                    'order_item_product_price', 'order_item_discount', 
                    'order_item_discount_rate', 'sales', 'order_item_total', 
                    'order_item_profit_ratio', 'benefit_per_order']].drop_duplicates(subset=['order_item_id']).reset_index(drop=True)

In [35]:
order_items.sample(5)

,order_item_id,order_id,product_card_id,order_item_quantity,order_item_product_price,order_item_discount,order_item_discount_rate,sales,order_item_total,order_item_profit_ratio,benefit_per_order
73502,119142,47652,1073,1,199.99,6.0,0.03,199.99,193.99,0.27,52.38
98790,106456,42651,1014,1,49.98,8.5,0.17,49.98,41.48,0.38,15.76
178986,16143,6448,1014,2,49.98,7.0,0.07,99.96,92.96,-2.30,-213.81
26816,11120,4444,93,2,24.99,1.5,0.03,49.98,48.48,0.35,16.97
157002,43167,17262,502,5,50.00,12.5,0.05,250.00,237.50,0.22,52.25

In [36]:
db.get_connection_string(db_name=None, user=None, password=None, host=None, port=None)

'mysql+pymysql://root:25401229@localhost:3306/'

#### Carga a SQL de dataco_supply_chain

In [37]:
db.create_database_if_not_exists("dataco")

✅ Base de datos 'dataco' verificada/creada con éxito.

In [38]:
db.load_dataframe_to_mysql(departments, "departments", "dataco")

✅ Datos cargados exitosamente en la tabla 'departments'.

In [39]:
db.set_primary_key("departments", "department_id", "dataco")

✅ Clave primaria 'department_id' (INT) asignada en 'departments'.

In [40]:
db.load_dataframe_to_mysql(categories, "categories", "dataco")

✅ Datos cargados exitosamente en la tabla 'categories'.

In [41]:
db.set_primary_key("categories", "category_id", "dataco")

✅ Clave primaria 'category_id' (INT) asignada en 'categories'.

In [42]:
db.load_dataframe_to_mysql(products, "products", "dataco")

✅ Datos cargados exitosamente en la tabla 'products'.

In [43]:
db.set_primary_key("products", "product_card_id", "dataco")

✅ Clave primaria 'product_card_id' (INT) asignada en 'products'.

In [44]:
db.set_foreign_key("products", "categories", "category_id", "dataco")

🔗 Relación creada: products.category_id ➡️ categories.category_id

In [45]:
db.load_dataframe_to_mysql(customers, "customers", "dataco")

✅ Datos cargados exitosamente en la tabla 'customers'.

In [46]:
db.set_primary_key("customers", "customer_id", "dataco")

✅ Clave primaria 'customer_id' (INT) asignada en 'customers'.

In [47]:
db.load_dataframe_to_mysql(orders, "orders", "dataco")

✅ Datos cargados exitosamente en la tabla 'orders'.

In [48]:
db.set_primary_key("orders", "order_id", "dataco")

✅ Clave primaria 'order_id' (INT) asignada en 'orders'.

In [49]:
db.set_foreign_key("orders", "customers", "customer_id", "dataco")

🔗 Relación creada: orders.customer_id ➡️ customers.customer_id

In [50]:
db.set_foreign_key("orders", "departments", "department_id", "dataco")

🔗 Relación creada: orders.department_id ➡️ departments.department_id

In [51]:
db.load_dataframe_to_mysql(order_items, "order_items", "dataco")

✅ Datos cargados exitosamente en la tabla 'order_items'.

In [52]:
db.set_primary_key("order_items", "order_item_id", "dataco")

✅ Clave primaria 'order_item_id' (INT) asignada en 'order_items'.

In [53]:
db.set_foreign_key("order_items", "orders", "order_id", "dataco")

🔗 Relación creada: order_items.order_id ➡️ orders.order_id

In [54]:
db.set_foreign_key("order_items", "products", "product_card_id", "dataco")

🔗 Relación creada: order_items.product_card_id ➡️ products.product_card_id

#### Carga a SQL de token_access_logs

In [55]:
df_token = pd.read_csv("../files/processed/token_access_logs.csv")

In [56]:
df_token.sample(5)

,product,category,department,ip,date,datetime
36089,Nike Men's Dri-FIT Victory Golf Polo,women's apparel,golf,107.146.231.8,12-05-2017,13:04
72568,Columbia Men's PFG Anchor Tough T-Shirt,shop by sport,golf,170.251.192.170,12-09-2017,07:44
158984,Under Armour Women's Ignite Slide,electronics,footwear,56.22.82.97,09-13-2017,20:28
65445,Nike Men's Dri-FIT Victory Golf Polo,women's apparel,golf,183.225.48.201,10-20-2017,16:00
463545,Perfect Fitness Perfect Rip Deck,cleats,apparel,99.237.181.177,10-08-2017,18:22

In [57]:
# Paso 1: Crea la columna 'id' asignándole el rango (sin reasignar df_token aquí)
df_token["id"] = range(1, len(df_token) + 1)

# Paso 2: Reorganiza las columnas para poner 'id' al principio
columnas = ["id"] + [col for col in df_token.columns if col != "id"]
df_token = df_token[columnas]

In [58]:
db.load_dataframe_to_mysql(df_token, "access_web", "dataco")

✅ Datos cargados exitosamente en la tabla 'access_web'.

In [59]:
db.set_primary_key("access_web", "id", "dataco", data_type="VARCHAR(25)")

✅ Clave primaria 'id' (VARCHAR(25)) asignada en 'access_web'.